name: Trigger issue creation from context

on:
  push:
  
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - run: | 
          curl -X POST \
          -H "Authorization: Bearer ${{ secrets.PAT }}" \
          -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/${{ github.repository }}/dispatches" \
          -d '{"event_type":"level_updated","client_payload":{"levels":["dev","test"]}}'
          echo ${{ github.repository }}...${{ github.event.repository }}
