name: Trigger issue creation from context

on:
  push:
  
jobs:

  trigger:
    runs-on: ubuntu-latest
    steps:
      - run: | 
          curl -X POST -H "authorization: Bearer ${{ secrets.PAT }}" \
          -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/${{ github.repository }}/actions/workflows/create-issues-from-context.yml/dispatches" \
          -d '{"event_type": "level_update", "client_payload": {"levels": ["dev","test"]}}'
